import type { Metadata } from "next";
import Header from '@/components/base/header';
import "./globals.css";
import 'normalize.css';
import Footer from '@/components/base/footer';

export const metadata: Metadata = {
  title:       "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main className="flex-1">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}